version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Redirigir el puerto 80 del host al puerto 80 del contenedor
    volumes:
      - ./nginx:/etc/nginx/conf.d  # Montar el directorio nginx para la configuración personalizada
    depends_on:
      - api
    networks:
      - mi_red_comun
  api:
    build:
      context: ./flask
    depends_on:
      - mongodb
    env_file:  # Añadir esta línea para especificar la ubicación del archivo .env
      - ./.env  # Ruta del archivo .env
    environment:
      - mongodb_ip=mongodb
    volumes:
      - ./logs:/app/logs  # Monta un directorio de logs del host en el contenedor
    networks:
      - mi_red_comun

  mongodb:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - mi_red_comun

  mosquitto:
    build: .
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - mi_red_comun

volumes:
  mongodb_data:
  mosquitto_data:
  mosquitto_log:
  nginx_log:
    driver: local

networks:
  mi_red_comun:
    driver: bridge