version: '3.8'
services:
  mqtt-client:
    build: .
    depends_on:
      - mongodb
    environment:
      - mongodb_ip=mongodb

  mongodb:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
