version: '3.9'
services:
  mqtt-client:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - mongodb_ip=mongodb
    networks:
      - mi_red_comun

  mongodb:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb_data:/data/db
    networks:
      - mi_red_comun

volumes:
  mongodb_data:

networks:
  mi_red_comun:
    external: true
