version: '3.9'

services:
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - api
    networks:
      - mi_red_comun

  api:
    build:
      context: ./flask
    container_name: api
    depends_on:
      - mongodb
    env_file:
      - ./.env
    environment:
      - mongodb_ip=mongodb
    volumes:
      - ./logs:/app/logs
    networks:
      - mi_red_comun

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - mi_red_comun

  mosquitto:
    build: .
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - mi_red_comun

volumes:
  mongodb_data:
  mosquitto_data:
  mosquitto_log:
  nginx_log:
    driver: local

networks:
  mi_red_comun:
